[package]
name = "num-bigfloat"
version = "1.5.0"
edition = "2021"
authors = ["stencillogic <stencillogic@gmail.com>"]
license = "MIT"
description = "Increased precision floating point numbers implemented purely in Rust."
categories = ["algorithms", "data-structures", "science"]
keywords = ["big-float", "numeric", "decimal", "mathematics", "bignum"]
readme = "README.md"
repository = "https://github.com/stencillogic/num-bigfloat"

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0"

[dependencies]
serde = { version = "~1.0.147", optional = true, default-features = false, features = ['derive'] }

[features]
default = ["std", "serde"]
std = ["serde/std"]
serde = ["dep:serde"]

[profile.release]
opt-level = 3
lto = true