name: Rust

on:
  push:
    branches: [ main, std_support ]
  pull_request:
    branches: [ main, std_support ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Run tests with no features and with no_std
      run: cargo test --release --verbose --no-default-features
    - name: Run tests with features serde num_traits and with no_std
      run: cargo test --release --no-default-features --features num-traits,serde